services:
  - type: web
    name: labelstudio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "label-studio start --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ALLOWED_HOSTS
        value: "labelstudio-app.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://labelstudio-app.onrender.com"
      - key: SSRF_PROTECTION_ENABLED
        value: "true"
      - key: DEBUG
        value: "true"
      - key: LABEL_STUDIO_HOST
        value: "https://labelstudio-app.onrender.com"
